sudo: true
language: c
addons:
  apt:
    sources:
#      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang
#      - clang-3.8
      - g++-5
      - gcc-5
script:
  - ./.travis.sh
matrix:
  include:
    - os: linux
      compiler: clang
#    - os: linux
#      compiler: clang-3.8
    - os: linux
      compiler: gcc-5
      compiler: gcc-5
#    - os: linux
#      compiler: clang-3.8
    - os: osx
      compiler: clang
